name: Build and deploy container app to Azure Web App - Scholarlytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: scholarlytics.azurecr.io
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: scholarlytics.azurecr.io/scholarlytics:${{ github.sha }}
        file: ./DockerFile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Scholarlytics'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_314618b18840452e9c698306ed218902 }}
        images: 'scholarlytics.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5f82d03b58c746c1bc2e9cb8a1378eab }}/scholarlytics:${{ github.sha }}'